include:
- file: gitlab-ci-template.yml
  project: devops/cicd-template/ci-template

variables:
  CI_CLUSTER_TYPE: INT-MON
  CI_APPLICATION_TYPE: GO
  CI_BRANCHING_TYPE: GITFLOW
  CI_IMAGE_REGISTRY: NEXUS
  CI_PROJECT_MODE: MONO
  CI_PROJECT_TYPE: BACKEND
  CI_RELEASE_TYPE: KANIKO
